"""Release validation tests.

These assert release-critical expectations: the package imports, the CLI entry
point exists, key docs and examples are present, the declared version is
consistent, and no forbidden attribution strings appear in tracked text files.
"""

import importlib
import subprocess
import tomllib
from pathlib import Path

import pytest

_REPO_ROOT = Path(__file__).resolve().parents[1]

_REQUIRED_DOCS = (
    "README.md",
    "docs/user_guide.md",
    "docs/testing.md",
)
_REQUIRED_EXAMPLES = (
    "examples/demos/startup_meeting_demo.py",
    "examples/datasets/company_memory_full.json",
)

_FORBIDDEN_STRINGS = (
    "co-authored-by",
    "cursor agent",
    "cursoragent",
    "generated by cursor",
    "ai-generated",
    "ai assistant",
)

_TEXT_SUFFIXES = {
    ".py",
    ".md",
    ".toml",
    ".txt",
    ".json",
    ".cfg",
    ".ini",
    ".yaml",
    ".yml",
    "",
}


def _tracked_files() -> list[Path]:
    output = subprocess.run(
        ["git", "ls-files"],
        cwd=_REPO_ROOT,
        capture_output=True,
        text=True,
        check=True,
    )
    return [_REPO_ROOT / line for line in output.stdout.splitlines() if line]


def test_package_imports() -> None:
    assert importlib.import_module("organizational_memory") is not None


def test_cli_main_exists() -> None:
    module = importlib.import_module("organizational_memory.cli.main")
    assert callable(module.main)
    assert callable(module.build_parser)


def test_required_docs_exist() -> None:
    for name in _REQUIRED_DOCS:
        assert (_REPO_ROOT / name).is_file(), name


def test_required_examples_exist() -> None:
    for name in _REQUIRED_EXAMPLES:
        assert (_REPO_ROOT / name).is_file(), name


def test_version_consistency() -> None:
    pyproject = tomllib.loads(
        (_REPO_ROOT / "pyproject.toml").read_text(encoding="utf-8")
    )
    declared = pyproject["project"]["version"]
    module = importlib.import_module("organizational_memory.version")
    assert module.__version__ == declared


def test_no_forbidden_attribution_strings() -> None:
    offenders: list[str] = []
    for path in _tracked_files():
        if path.name == Path(__file__).name:
            continue
        if path.suffix not in _TEXT_SUFFIXES:
            continue
        try:
            text = path.read_text(encoding="utf-8").lower()
        except (OSError, UnicodeDecodeError):
            continue
        for needle in _FORBIDDEN_STRINGS:
            if needle in text:
                offenders.append(f"{path.relative_to(_REPO_ROOT)}: {needle}")
    assert offenders == [], offenders


@pytest.mark.parametrize("needle", _FORBIDDEN_STRINGS)
def test_forbidden_list_is_lowercase(needle: str) -> None:
    assert needle == needle.lower()
