"""Deterministic post-release verification.

Run after tagging and building to confirm the release is intact: the local tag
exists, the commit count matches, build artifacts are present, release docs and a
versioned changelog section exist, and tracked text files contain no tool
attribution.

Usage::

    python scripts/post_release_verification.py
"""

from __future__ import annotations

import subprocess
import sys
from collections.abc import Iterable
from dataclasses import dataclass
from pathlib import Path

_REPO_ROOT = Path(__file__).resolve().parents[1]

EXPECTED_VERSION = "0.1.0"
EXPECTED_TAG = "v0.1.0"
EXPECTED_COMMIT_COUNT = 225

RELEASE_DOCS = (
    "docs/releases/v0.1.0.md",
    "docs/releases/latest.md",
    "docs/release_checklist.md",
)
# Built from fragments so this source file does not itself contain the
# contiguous markers it scans for.
FORBIDDEN_STRINGS = (
    "co-" + "authored-by",
    "cursor" + " agent",
    "cursor" + "agent",
    "generated by " + "cursor",
    "ai-" + "generated",
    "ai " + "assistant",
)
_TEXT_SUFFIXES = {
    ".py", ".md", ".toml", ".txt", ".json", ".cfg", ".ini", ".yaml", ".yml", "",
}
_ATTRIBUTION_ALLOWLIST = {
    "tests/test_release_validation.py",
    "scripts/run_release_validation.py",
    "scripts/post_release_verification.py",
}


@dataclass(frozen=True)
class CheckResult:
    """The outcome of a single post-release check."""

    name: str
    passed: bool
    detail: str


def verify_tag_exists(tags: Iterable[str], tag: str = EXPECTED_TAG) -> bool:
    """Return whether ``tag`` is present in ``tags``."""
    return tag in set(tags)


def verify_commit_count(actual: int, expected: int = EXPECTED_COMMIT_COUNT) -> bool:
    """Return whether the actual commit count matches the expected value."""
    return actual == expected


def verify_build_artifacts(dist_dir: Path) -> bool:
    """Return whether a wheel and a source distribution exist in ``dist_dir``."""
    if not dist_dir.is_dir():
        return False
    has_wheel = any(dist_dir.glob("*.whl"))
    has_sdist = any(dist_dir.glob("*.tar.gz"))
    return has_wheel and has_sdist


def verify_release_docs(root: Path = _REPO_ROOT) -> list[str]:
    """Return the list of missing release docs (empty when all are present)."""
    return [name for name in RELEASE_DOCS if not (root / name).is_file()]


def verify_changelog_has_version(text: str, version: str = EXPECTED_VERSION) -> bool:
    """Return whether the changelog text contains a section for ``version``."""
    return f"[{version}]" in text or f"## {version}" in text


def scan_forbidden(paths: Iterable[Path], root: Path = _REPO_ROOT) -> list[str]:
    """Return ``path: needle`` offenders for forbidden attribution strings."""
    offenders: list[str] = []
    for path in paths:
        if path.suffix not in _TEXT_SUFFIXES:
            continue
        try:
            text = path.read_text(encoding="utf-8").lower()
        except (OSError, UnicodeDecodeError):
            continue
        for needle in FORBIDDEN_STRINGS:
            if needle in text:
                try:
                    label = path.relative_to(root)
                except ValueError:
                    label = path
                offenders.append(f"{label}: {needle}")
    return offenders


def _git_lines(args: list[str], root: Path) -> list[str]:
    result = subprocess.run(
        ["git", *args], cwd=root, capture_output=True, text=True, check=True
    )
    return [line for line in result.stdout.splitlines() if line]


def run_all(root: Path = _REPO_ROOT) -> list[CheckResult]:
    """Run every post-release check and return the results."""
    tags = _git_lines(["tag", "--list"], root)
    commit_count = len(_git_lines(["rev-list", "HEAD"], root))
    tracked = [
        root / line
        for line in _git_lines(["ls-files"], root)
        if line not in _ATTRIBUTION_ALLOWLIST
    ]
    missing_docs = verify_release_docs(root)
    changelog = (root / "CHANGELOG.md").read_text(encoding="utf-8")
    offenders = scan_forbidden(tracked, root)
    return [
        CheckResult("tag_exists", verify_tag_exists(tags), f"tag={EXPECTED_TAG}"),
        CheckResult(
            "commit_count",
            verify_commit_count(commit_count),
            f"actual={commit_count} expected={EXPECTED_COMMIT_COUNT}",
        ),
        CheckResult(
            "build_artifacts",
            verify_build_artifacts(root / "dist"),
            "dist/ contains a wheel and an sdist",
        ),
        CheckResult(
            "release_docs",
            not missing_docs,
            "all present" if not missing_docs else f"missing: {missing_docs}",
        ),
        CheckResult(
            "changelog_version",
            verify_changelog_has_version(changelog),
            f"version={EXPECTED_VERSION}",
        ),
        CheckResult(
            "attribution_scan",
            not offenders,
            "clean" if not offenders else f"offenders: {offenders}",
        ),
    ]


def format_report(results: list[CheckResult]) -> str:
    """Build a human-readable post-release report."""
    lines = ["Post-release verification", ""]
    for result in results:
        status = "PASS" if result.passed else "FAIL"
        lines.append(f"  {status} {result.name}: {result.detail}")
    return "\n".join(lines)


def main(argv: list[str] | None = None) -> int:
    """Run post-release verification and print a report."""
    results = run_all()
    print(format_report(results))
    return 0 if all(result.passed for result in results) else 1


if __name__ == "__main__":
    sys.exit(main())
