"""Deterministic release validation orchestrator.

Runs a set of local, offline checks that gate a release: package verification,
version consistency, required docs and examples, a forbidden-attribution scan, a
commit-count check, and tag readiness. Each check returns a :class:`CheckResult`;
the script exits non-zero if any check fails.

Usage::

    python scripts/run_release_validation.py
"""

from __future__ import annotations

import subprocess
import sys
import tomllib
from collections.abc import Iterable
from dataclasses import dataclass
from pathlib import Path

_REPO_ROOT = Path(__file__).resolve().parents[1]

EXPECTED_VERSION = "0.1.0"
EXPECTED_COMMIT_COUNT = 225

REQUIRED_DOCS = (
    "README.md",
    "CHANGELOG.md",
    "docs/index.md",
    "docs/user_guide.md",
    "docs/releases/v0.1.0.md",
)
REQUIRED_EXAMPLES = (
    "examples/demos/startup_meeting_demo.py",
    "examples/tutorials/tutorial_01_ingest_and_extract.py",
    "examples/datasets/company_memory_full.json",
)
# Built from fragments so this source file does not itself contain the
# contiguous markers it scans for.
FORBIDDEN_STRINGS = (
    "co-" + "authored-by",
    "cursor" + " agent",
    "cursor" + "agent",
    "generated by " + "cursor",
    "ai-" + "generated",
    "ai " + "assistant",
)
_TEXT_SUFFIXES = {
    ".py", ".md", ".toml", ".txt", ".json", ".cfg", ".ini", ".yaml", ".yml", "",
}
# Files that legitimately define the forbidden markers (to scan for them) and so
# must be excluded from the scan itself.
_ATTRIBUTION_ALLOWLIST = {
    "tests/test_release_validation.py",
    "scripts/run_release_validation.py",
}


@dataclass(frozen=True)
class CheckResult:
    """The outcome of a single release-validation check."""

    name: str
    passed: bool
    detail: str


def read_pyproject_version(root: Path = _REPO_ROOT) -> str:
    """Return the ``project.version`` from ``pyproject.toml``."""
    data = tomllib.loads((root / "pyproject.toml").read_text(encoding="utf-8"))
    version = data["project"]["version"]
    if not isinstance(version, str):  # pragma: no cover - defensive guard
        raise TypeError("project.version must be a string")
    return version


def check_version_consistency(
    pyproject_version: str, module_version: str, expected: str = EXPECTED_VERSION
) -> CheckResult:
    """Verify the pyproject and module versions match the expected value."""
    passed = pyproject_version == module_version == expected
    return CheckResult(
        "version_consistency",
        passed,
        f"pyproject={pyproject_version} module={module_version} expected={expected}",
    )


def check_required_paths(
    names: Iterable[str], label: str, root: Path = _REPO_ROOT
) -> CheckResult:
    """Verify every relative path in ``names`` exists under ``root``."""
    missing = [name for name in names if not (root / name).is_file()]
    if missing:
        return CheckResult(label, False, f"missing: {missing}")
    return CheckResult(label, True, f"found {len(tuple(names))} files")


def scan_forbidden(paths: Iterable[Path], root: Path = _REPO_ROOT) -> list[str]:
    """Return ``path: needle`` offenders for forbidden attribution strings."""
    offenders: list[str] = []
    for path in paths:
        if path.suffix not in _TEXT_SUFFIXES:
            continue
        try:
            text = path.read_text(encoding="utf-8").lower()
        except (OSError, UnicodeDecodeError):
            continue
        for needle in FORBIDDEN_STRINGS:
            if needle in text:
                try:
                    label = path.relative_to(root)
                except ValueError:
                    label = path
                offenders.append(f"{label}: {needle}")
    return offenders


def check_commit_count(
    actual: int, expected: int = EXPECTED_COMMIT_COUNT
) -> CheckResult:
    """Verify the actual commit count matches the expected value."""
    return CheckResult(
        "commit_count", actual == expected, f"actual={actual} expected={expected}"
    )


def tag_is_ready(existing_tags: Iterable[str], tag: str) -> bool:
    """Return whether ``tag`` is ready to be created (not already present)."""
    return tag not in set(existing_tags)


def check_tag_readiness(existing_tags: Iterable[str], tag: str) -> CheckResult:
    """Verify the release tag has not been created yet."""
    ready = tag_is_ready(existing_tags, tag)
    return CheckResult("tag_readiness", ready, f"tag={tag} ready={ready}")


def _git_lines(args: list[str], root: Path) -> list[str]:
    result = subprocess.run(
        ["git", *args], cwd=root, capture_output=True, text=True, check=True
    )
    return [line for line in result.stdout.splitlines() if line]


def _module_version() -> str:
    from organizational_memory.version import __version__

    return __version__


def run_all(root: Path = _REPO_ROOT) -> list[CheckResult]:
    """Run every release-validation check and return the results."""
    tracked = [
        root / line
        for line in _git_lines(["ls-files"], root)
        if line not in _ATTRIBUTION_ALLOWLIST
    ]
    commit_count = len(_git_lines(["rev-list", "HEAD"], root))
    tags = _git_lines(["tag", "--list"], root)
    offenders = scan_forbidden(tracked, root)
    return [
        check_version_consistency(read_pyproject_version(root), _module_version()),
        check_required_paths(REQUIRED_DOCS, "required_docs", root),
        check_required_paths(REQUIRED_EXAMPLES, "required_examples", root),
        CheckResult(
            "attribution_scan",
            not offenders,
            "clean" if not offenders else f"offenders: {offenders}",
        ),
        check_commit_count(commit_count),
        check_tag_readiness(tags, f"v{EXPECTED_VERSION}"),
    ]


def format_report(results: list[CheckResult]) -> str:
    """Build a human-readable release-validation report."""
    lines = ["Release validation", ""]
    for result in results:
        status = "PASS" if result.passed else "FAIL"
        lines.append(f"  {status} {result.name}: {result.detail}")
    return "\n".join(lines)


def main(argv: list[str] | None = None) -> int:
    """Run release validation and print a report."""
    results = run_all()
    print(format_report(results))
    return 0 if all(result.passed for result in results) else 1


if __name__ == "__main__":
    sys.exit(main())
